### ISSUE TITLE
Requests with response_mode set to form_post

### ISSUE THREAD

**Issue by fonsecas72** [vaulttec/sonar-auth-oidc#11]
Hi, I asked the partner regarding my issue and I was told that the request is being received without the "response_mode" set to "form_post" and they told me it should according to this spec https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

Could you please elucidate me?

Relates to : 
https://github.com/vaulttec/sonar-auth-oidc/issues/3#issuecomment-387497143

**Comment by tjuerge** [comment]
This plugin implements the [Authorization Code Flow](http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth) of the Open ID Connect Core Spec. Here the [authentication request](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) defines the optional request parameter `request_mode`. If this parameter is omitted (like with this plugin) then the default mode `query` is assumed. In this case the access codes are returned by the authentication server as query parameters of a GET request.

The mentioned form post response mode spec is an OIDC extension which specifies a new value for the authentication request parameter `request_mode` - `form_post`. In this case the access codes are returned by the authentication server as HTML code with a post form.

This spec is an optional extension. So there's no guarantee that it's supported by all partners.


Please check with your partner why it's access server doesn't support the plain vanilla Authorization Code Flow (`request_mode` omitted - meaning default mode `query`) as defined in the Open ID Connect Core Spec.
