### ISSUE TITLE
Proxy usage

### ISSUE THREAD

**Issue by pauxus** [vaulttec/sonar-auth-oidc#14]
Scenario:

- SonarQube configured with proxy to access update site
- internal Keycloak (not behind the proxy)
- http.nonProxy is set in sonar.properties
- Request is still routed through the proxy and thus fails

Solution:
- Either honor nonProxy property (if used at all) or add another configuration parameter to configure whether the proxy should be used.

Cheers,

Stephan

**Comment by tjuerge** [comment]
> http.nonProxy is set in sonar.properties

It seems your're looking for the property [`http.nonProxyHosts`](https://github.com/SonarSource/sonarqube/blob/2b0f05f4442cb3e3b9c798adf9d93f64e19a6b01/server/sonar-process/src/main/java/org/sonar/process/ProcessProperties.java#L79) :-)

An example can be found [here](https://github.com/SonarSource/sonarqube/blob/6f13f93ffca506f08f5c55421a069590f170f97f/server/sonar-server/src/main/resources/org/sonar/server/platform/ws/info-example.json#L120).

**Comment by pauxus** [comment]
Argh... This comes from doing two many things at once... You are right, of course.
