### ISSUE TITLE
Add Setting for Additional Scopes

### ISSUE THREAD

**Issue by BrentSouza** [vaulttec/sonar-auth-oidc#16]
First please let me say thank you for your work on this plugin!

We are using Okta as our OIDC provider and they require that one pass a "groups" scope in order to return the group claims with the id token. If there were a setting for this plugin that allowed a user to define additional scopes to send along with the authorize request, we would be able to use the group syncing feature!

Do you think it would be possible to add this as a feature?

**Comment by tjuerge** [comment]
Fixed in #17
