### ISSUE TITLE
Add support to change openid.svg

### ISSUE THREAD

**Issue by grizzly-monkey** [vaulttec/sonar-auth-oidc#19]
Like change the name to company SSO would be great to have configurable svg /ico for company sso.

**Comment by MatteoJoliveau** [comment]
I second this

**Comment by tjuerge** [comment]
> I second this, or at least change the label to "Log in with SSO" or something like that

Something like this? ;-)
<img width="1193" alt="Screenshot 2019-11-02 at 21 46 20" src="https://user-images.githubusercontent.com/2626998/68076823-4bdc8b80-fdba-11e9-970a-a8335483508c.png">
