### ISSUE TITLE
Build new release containing sonar.auth.oidc.additionalScopes and sonar.auth.oidc.loginButtonText changes

### ISSUE THREAD

**Issue by hibbert** [vaulttec/sonar-auth-oidc#22]
Hi,

We have had to build are own jar manually as we needed the commits below to get the additional scoped and login button text changes. Please could you build a new release?

https://github.com/vaulttec/sonar-auth-oidc/pull/17
https://github.com/vaulttec/sonar-auth-oidc/commit/c46c770a8e4bfd88f8ecc0687cd3312109c1c6bf

Thanks

**Comment by tjuerge** [comment]
Version 1.1.0 released
