### ISSUE TITLE
Fetch OpenID Connect Provider from url

### ISSUE THREAD

**Issue by lhotrifork** [vaulttec/sonar-auth-oidc#23]
Hi,

Thanks for a nice plugin.
It would be useful if the plugin could fetch OpenID Connect Provider info from a URL instead of having to copy/paste JSON when configuring OpenID in SonarQube.

This request is triggered by an update to the sonarqube helmchart: https://github.com/helm/charts/issues/15094 where it's no longer possible to embed JSON in the values.

Kind regards,
Lasse

**Comment by LinuxSuRen** [comment]
I configured this done. But met another problem. It's ok except that I can see the configuration from WebUI. It looks like the security page is empty.

**Comment by lainosantos** [comment]
Hello,

This is a good feature, any news here?
