### ISSUE TITLE
can you update guide for sonar.properties ?

### ISSUE THREAD

**Issue by Hokwang** [vaulttec/sonar-auth-oidc#26]
Hello.

Thanks for this plugin.
I will use keycloak with sonarqube,

README.md shows configs in web page, but I need sonar.properties setting for
config as code.

Please update simple example for sonar.properties.

Thanks.

**Comment by usualstuff** [comment]
Hi. I think you can look at code itself: https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcSettings.java#L43
