### ISSUE TITLE
Is it possible to pass the Client Secret as Env Var?

### ISSUE THREAD

**Issue by cten** [vaulttec/sonar-auth-oidc#33]
Trying to secure my deployment to kubernetes and don't want the client secret in my git repo is possible. I tried to pass `SONAR_AUTH_OIDC_CLIENTSECRET_SECURED` but didn't seem to work.

**Comment by tjuerge** [comment]
I'm not aware of any automagically handling of env vars (like Spring Boot is doing) in SQ.

How about adding `sonar.auth.oidc.clientSecret.secured=<client secret>` to `sonar.properties`?
Or maybe it's possible to use Java system properties like `-Dsonar.auth.oidc.clientSecret.secured=<client secret>` in the command used for starting SQ's Java process.
