### ISSUE TITLE
You're not authorized to access this page. Please contact the administrator.

### ISSUE THREAD

**Issue by Haso58** [vaulttec/sonar-auth-oidc#36]
Hi,

I followed everything from the step by step but in the end I am getting an error "you are not authorized to see this page"

What can I do?

**Comment by jomu78** [comment]
I have the same issue, Keycloak returns Token request failed: {"error_description":"Code not valid","error":"invalid_grant"} (Exception in sonar-web.log)

**Comment by lorenzstadler** [comment]
I had the same error and could find the root cause in the sonarqube logs. In the SonarQube settings, you can set the log level to "TRACE", then try to authenticate again and check the log.

**Comment by jomu78** [comment]
on our end it was a problem with the reverse proxies and the load balancing of the keycloak cluster. The sonar configuration using the plugin was correct.

**Comment by tjuerge** [comment]
As suggested by @lorenzstadler change SQ's log level and check SQ's logs.
Additionally as mentioned by @jomu78 check the configuration / logs of your IdP and web server.
