### ISSUE TITLE
Is there any way to skip the ssl verification when use https？

### ISSUE THREAD

**Issue by yuzp1996** [vaulttec/sonar-auth-oidc#37]
Hello! I find the latest code verison use nimbusds-oidc-sdk:6.23. and nimbusds-oidc-sdk:6.23 now should have support disable SSL 

[nimbusds-oidc-sdk changlog](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/aa9e8dcc9e9b8891f3c847b4de756509a8e036f6/CHANGELOG.txt#lines-1109)

but how can I disable ssl verification with this plugin?

**Comment by tjuerge** [comment]
IMHO this is not a concern of the plugin.

Please import the certificate chain of the CA which signed the CSR for your server certificate in SQ's Java keystore.
