### ISSUE TITLE
Groups claim isn't returned in the ID token for OKTA

### ISSUE THREAD

**Issue by taha-au** [vaulttec/sonar-auth-oidc#40]
We use Okta as our IdP and for OIDC to work with Okta, a further call needs to be made to the `/userinfo` endpoint to get the groups info since Okta doesn't encode that claim into the token.

**Comment by taha-au** [comment]
This issue is addressed in https://github.com/autonomic-ai/sonar-auth-oidc/pull/1

**Comment by moroienius** [comment]
i've confirm same issue when using Okta.After applying fix from [#39](https://github.com/vaulttec/sonar-auth-oidc/pull/39) i got groups fine

**Comment by tjuerge** [comment]
Merged #39 - thanks @taha-au
