### ISSUE TITLE
Set oidc value in sonar.property and SSO work. But values cannot find in settings

### ISSUE THREAD

**Issue by yuzp1996** [vaulttec/sonar-auth-oidc#43]
I use sonar.property to set the oidc values, when I start sonarqube, I can login with oidc. But  when I check the values in settings, I find the values for oidc are all blank.   Is this a bug or anything I can do to resolve this problem.

Thank you very much!

**Comment by tjuerge** [comment]
`sonar.properties` is only intended for system settings and this file is read-only (values here can't be changed via UI). A detailed explanation can be found in [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818).
