### ISSUE TITLE
Groups aren't syncing

### ISSUE THREAD

**Issue by cten** [vaulttec/sonar-auth-oidc#48]
I have the "Synchronize groups" set to "true" but even though I have groups with the same names in both my ID Provider and Sonar the users are only getting added to the default group of sonar-users.

Sonar version: 8.2
Plugin version 2.0.0

**Comment by fbuchmeier** [comment]
Hi cten,

what did you do to fix your issue with group sync not working?

Thanks and regards,
Florian.

**Comment by cten** [comment]
Seems I just needed to add groups to the scope:
`sonar.auth.oidc.scopes=openid,email,profile,groups`

**Comment by iamrahul127** [comment]
We are also facing same challenge with Azure OpenId Connect integration. We could get it integrated but group synchronization is not working. By any chance you have integrated with Azure? If yes can you help?
