### ISSUE TITLE
 Invalid ID token

### ISSUE THREAD

**Issue by burgessjp** [vaulttec/sonar-auth-oidc#59]
SonarQube Version: 9.0.1

![image](https://user-images.githubusercontent.com/10663475/143522604-8cbd11fd-0b52-45b0-aa4b-da63b08684e1.png)

**Comment by burgessjp** [comment]
@tjuerge Need Help.

**Comment by tjuerge** [comment]
This screenshot is pretty useless - the infos regarding the received ID token and the [wrapped root `BadJOSEException`](https://github.com/vaulttec/sonar-auth-oidc/blob/99d8604440c48d4960a30c9cb487412cd766edea/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcClient.java#L189) are missing here. Please activate SQ's trace logging and add the logging of the plugin (by removing all the SQ logging, e.g. via `grep`) as shown [here](https://github.com/vaulttec/sonar-auth-oidc#troubleshooting).

And which OpenID Connect identity provider are you using?

**Comment by tjuerge** [comment]
And check if your identity provider has signed the ID token with the same algorithm (HMAC, RSA or ECDSA) as you selected in the plugin configuration `ID token signature algorithm`. If your're unsure then deactivate this feature.

**Comment by tjuerge** [comment]
Its seems your identity provider is signing with HMAC because the JWT of your ID token header `eyJhbGciOiJIUzI1NiJ9` contains
```json
{
  "alg": "HS256"
}
```
This is in accordance with the log message `Validating ID Token with HS256 and...`. Did you select `HMAC` for the plugin configuration `ID token signature algorithm`?

**Comment by burgessjp** [comment]
> Its seems your identity provider is signing with HMAC because the JWT of your ID token header `eyJhbGciOiJIUzI1NiJ9` contains
> 
> ```json
> {
>   "alg": "HS256"
> }
> ```
> 
> This is in accordance with the log message `Validating ID Token with HS256 and...`. Did you select `HMAC` for the plugin configuration `ID token signature algorithm`?

Yes,
The Configration is OK.

**Comment by tjuerge** [comment]
Ok, then only the full stacktrace (including the wrapped [`BadJOSEException`](https://github.com/vaulttec/sonar-auth-oidc/blob/99d8604440c48d4960a30c9cb487412cd766edea/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcClient.java#L189)) can give us a hint. Please post the full stacktrace - or the wrapped root exception of the `IllegalStateException`.

Btw. you can deactivate the plugin's ID token validation by selecting `None` instead of `HMAC` as `ID token signature algorithm`. Is this mode working for you?

**Comment by tjuerge** [comment]
The wrapped [`BadJOSEException`](https://github.com/vaulttec/sonar-auth-oidc/blob/99d8604440c48d4960a30c9cb487412cd766edea/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcClient.java#L189) is thrown in Nimbus JOSE JWT's [`DefaultJWTProcessor`](https://javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/9.15.2/src-html/com/nimbusds/jwt/proc/DefaultJWTProcessor.html). Here you can find all the different error messages and the corresponding JWT object validations.
A detailed explanation of the inner workings of validating signed ID Tokens can be found [here](https://curity.io/resources/learn/validating-an-id-token/).

Which identity provider are you using?

**Comment by burgessjp** [comment]
@tjuerge 

Thank you for your answer, this identity provider is our own company, I am looking for their assistance.

I will sync here when there is a result.
