### ISSUE TITLE
preferred_username is not requested 

### ISSUE THREAD

**Issue by jocsch** [vaulttec/sonar-auth-oidc#6]
Currently **name** and **preferred_username** are mandatory to make the _getUser_ method work (https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/UserIdentityFactory.java)

However in our IdP implementation none of these is contained in the id_token because none is asked for in the oidc-login request.

The spec says:

> Pre-defined sets of Claims can be requested using specific scope values or individual Claims can be requested using the claims request parameter. The Claims can come directly from the OpenID Provider or from distributed sources as well.

Defined in ch. 5.4&5.5

So I suppose there is a _claims_ parameter required with a json containing the id_token attribute.

**Comment by tjuerge** [comment]
In [`OidcClient.getAuthenticationRequest()`](https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcClient.java#L71) the claims are requested via the scope values `openid profile email`. The authentication request uses `request_type` token value of `id_token`.

[As per spec](http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) the IdP should return an ID token with the End-User's default profile claims (including `nickname` or `preferred_username`). If not returned in the ID token then these claims must be available from the user info endpoint ([called by `OidcClient`](https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/OidcClient.java#L135) if the claims `name` and `preferred_username` are not present in the ID token.

Ok, back to reality ;-)

What IdP are you using?  Does it's documentation provide any indication about support for (via scope) requested claims in the ID token like Keycloak does with it's [OIDC Token and SAML Assertion Mappings](http://www.keycloak.org/docs/3.3/server_admin/topics/clients/protocol-mappers.html)?

Is there any chance you can provide a SonarQube `web.log` with `sonar.log.level.web` set to `DEBUG`?

At the end of the day we have to debug your IdP implementation as we did in #3. Hopefully we can add your IdP to the list ["Tested with"](https://github.com/vaulttec/sonar-auth-oidc#tested-with) as well :-)

**Comment by jocsch** [comment]
You are right. I have always missed the profile claim definition in the spec.
We have a server based on connect2id which delegates scope handling to a custom implementation.
I guess we have to fix it there.
