### ISSUE TITLE
Allow using a separate claim as name

### ISSUE THREAD

**Issue by mfriedenhagen** [vaulttec/sonar-auth-oidc#62]
- Right now it seems the plugin does use `sonar.auth.oidc.loginStrategy` for both the `login` and `name` of a user (so in my case here in GitHub it would be `mfriedenhagen` both times).
- It would be great if one could provide another claim for `name`, maybe even a claim combination (`${given_name} ${family_name}`)

**Comment by tjuerge** [comment]
> Right now it seems the plugin does use `sonar.auth.oidc.loginStrategy` for both the `login` and `name` of a user (so in my case here in GitHub it would be `mfriedenhagen` both times).

For a `sonar.auth.oidc.loginStrategy` of `Preferred username` the `login` and `name` are the same (the preferred usename) if the identity provider [is not providing the claim `name`](https://github.com/vaulttec/sonar-auth-oidc/blob/master/src/main/java/org/vaulttec/sonarqube/auth/oidc/UserIdentityFactory.java#L93) or the provided claims `name` and `preferred_username` are identical. Further details can be found [here](https://github.com/vaulttec/sonar-auth-oidc/issues/6#issuecomment-369765116).

Which identity provider are you using? Is there any chance you can provide a SonarQube `web.log` with `sonar.log.level.web` set to `DEBUG`as described [here](https://github.com/vaulttec/sonar-auth-oidc#troubleshooting)?

> It would be great if one could provide another claim for `name`, maybe even a claim combination (`${given_name} ${family_name}`)

This kind of claim mapping is expected to be done by the identity provider, e.g. like Keycloak does with it's [OIDC token and SAML assertion mappings](https://www.keycloak.org/docs/latest/server_admin/#_protocol-mappers).

There must be a reason why your identy provider is not providing the claim `name` aligned to [the OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) (... _name | string | End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences._ ...).

**Comment by mfriedenhagen** [comment]
Thanks for the quick answer and the links. The IdP I use developed in-house, I will talk about this problem with the team in charge.
