### ISSUE TITLE
problem sincronyzing groups

### ISSUE THREAD

**Issue by gt97** [vaulttec/sonar-auth-oidc#67]
I am using the plugin version 2.1.1 on sonarqube version 8.9.2. I copied the jar in extensions\plugins
 I am not able to sincronyze the AD groups.
 The login of the user is OK.

 My configuration is:
Scopes --> openid email profile
ID token signature algorithm --> blank
Allow users to sign-up --> true
Login generation strategy --> Preferred username
Login strategy custom claim --> upn
Synchronize groups --> true
Groups claim name --> groups

I created a group in Sonarqube called TFS-ADMIN_C
When I login with a user that has TFS-ADMIN_C the user is not added to the group

The log (in trace mode) shows that the groups are in the response in json format.
This is the log (extracting o.v.s)
[log.txt](https://github.com/vaulttec/sonar-auth-oidc/files/11345458/log.txt)

Any help?

**Comment by tjuerge** [comment]
> The log (in trace mode) shows that the groups are in the response in json format.

The groups list needs to be formatted as a JSON array instead of a string containing a JSON array:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/2626998/235300532-d9fe783d-6e8a-411b-a28a-1bc8cf489ef5.png">

**Comment by tjuerge** [comment]
From the plugin's README:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/2626998/235300761-18a3fbfe-acc1-468e-be15-87bbb6b39ae4.png">
