### ISSUE TITLE
Automatic setup

### ISSUE THREAD

**Issue by Jufik** [vaulttec/sonar-auth-oidc#68]
Thanks for the amazing config, that is pretty awesome.
Deploying the plugin with the official Helm chart, I am looking for a way to _automatically_ configure your plugins.

Any guidance on how this could be done using some script during init ?

**Comment by tjuerge** [comment]
As mentioned in #43 I'm not aware of any way to provide plugin configuration other than manually via Sonarqube's admin UI. This is explained in the answer to the community question [SSO Configuration not showing in UI](https://community.sonarsource.com/t/sso-configuration-not-showing-in-ui-v8-9-1-community-edition/45656).
