### ISSUE TITLE
OpenID Connect Provider configuration

### ISSUE THREAD

**Issue by alishah730** [vaulttec/sonar-auth-oidc#9]
Please help with the OpenID Connect Provider configuration complete JSON

**Comment by alishah730** [comment]
below is the error in the log

2018.04.17 15:14:42 ERROR web[AWLS+xKhk/ZC7Y1yAAAz][o.s.s.a.AuthenticationError] Fail to initialize authentication with provider 'oidc'
java.lang.IllegalStateException: Invalid OpenID Connect provider configuration
	at org.vaulttec.sonarqube.auth.oidc.OidcClient.getProviderMetadata(OidcClient.java:185)


my config is ::

{
"issuer":"https://sample.com/sso",
"authorization_endpoint":"https://sample.com/sso/as/authorization.oauth2",
"token_endpoin":"https://sample.com/sso/as/token.oauth2"
}

**Comment by alishah730** [comment]
Caused by: com.nimbusds.oauth2.sdk.ParseException: Missing JSON object member with key "subject_types_supported"
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:120)
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getList(JSONObjectUtils.java:399)

**Comment by tjuerge** [comment]
This [OpenID Connect provider metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) can be retrieved from your OIDC provider via the [`/.well-known/openid-configuration` URL](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig), e.g.
```
$ curl -s https://localhost:9031/.well-known/openid-configuration|python -m json.tool
{
    "authorization_endpoint": "https://localhost:9031/as/authorization.oauth2",
    ...
    "claims_supported": [
        "address",
        ...
     ],
    "id_token_signing_alg_values_supported": [
        "none",
        ...
     ],
    "issuer": "https://localhost:9031",
    "jwks_uri": "https://localhost:9031/pf/JWKS",
    "ping_end_session_endpoint": "https://localhost:9031/idp/startSLO.ping",
    "ping_revoked_sris_endpoint": "https://localhost:9031/pf-ws/rest/sessionMgmt/revokedSris",
    ...
    "revocation_endpoint": "https://localhost:9031/as/revoke_token.oauth2",
    ...
    "token_endpoint": "https://localhost:9031/as/token.oauth2",
    ...
    "userinfo_endpoint": "https://localhost:9031/idp/userinfo.openid",
    ...
}
```
